Logger:
  # 日志输出位置
  FileName: ./logs/cppsvr.log
  # 一个日志文件最多的字节数（这里设置 4MB）
  MaxSize: 4194304
  # 日志器输出日志的最低等级
  Level: DEBUG
  # 是否在控制台展示
  Console: true

Coroutine:
  # 默认的协程栈大小 2 KB
  StackSize: 2097152

ThreadPool:
  # 工作线程数
  ThreadNum: 4

