Logger:
  # 日志输出位置（默认 ./logs/cppsvr.log）
  FileName: ./logs/cppsvr.log
  # 一个日志文件最多的字节数（这里设置 4MB，默认 4MB）
  MaxSize: 4194304
  # 日志器输出日志的最低等级（默认 DEBUG）
  Level: DEBUG
  # 是否在控制台展示（默认 true）
  Console: true

Coroutine:
  # 工作线程数（默认 1）
  ThreadNum: 4
  # 单个工作线程的协程数（默认 100）
  CoroutineNum: 100
  # 协程栈大小（这里 64 KB，默认 128 KB）
  StackSize: 65536

