Logger:
  # 日志输出位置（默认 ./logs/cppsvr.log）
  FileName: ./logs/cppsvr.log
  # 一个日志文件最多的字节数（这里设置 4MB，默认 4MB）
  MaxSize: 4194304
  # 日志器输出日志的最低等级（默认 DEBUG）
  Level: WARN
  # 是否在控制台展示（默认 true）
  Console: true

Server:
  # ip（默认 0.0.0.0）
  IP: 127.0.0.1
  # 端口（默认 8888）
  Port: 1335
  # 是否复用地址（允许关闭后立即重启服务，即使前面的还在 time_wait 状态。默认为 false）
  ReuseAddr: true
  # 工作线程数，也即子响应器数（默认 1）
  WorkerThreadNum: 4
  # 单个工作线程的协程池中的协程数（默认 100）
  WorkerCoroutineNum: 100
  # 单个协程的栈大小（这里 64 KB，默认 128 KB）
  StackSize: 65536


